#pragma once

// place overrides here
#define PERMISSIVE_HOLD
#define TAPPING_TERM 150

#undef USB_MAX_POWER_CONSUMPTION
#define USB_MAX_POWER_CONSUMPTION 500

#undef USB_POLLING_INTERVAL_MS
#define USB_POLLING_INTERVAL_MS 10